services:

  sqlserver-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/1433'"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 20s
      
  
  init-db:
    image: mcr.microsoft.com/mssql-tools
    container_name: initdbcontainer
    depends_on:
      sqlserver-db:
        condition: service_healthy
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
    volumes:
      - ./db/init.sql:/init.sql:ro
      
    entrypoint: >
      /bin/bash -c "
      /opt/mssql-tools/bin/sqlcmd -S sqlserver-db -U sa -P \"$$SA_PASSWORD\" -b -i /init.sql
      "
        
    restart: "no"
    
  auth:
    build:
      context: ./AuthService
    container_name: authcontainer
    environment: 
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://sqlserver-db:1433;databaseName=DBMAGAZZINI;encrypt=true;trustServerCertificate=true"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "Magazzinetto34*"
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      SPRING_JPA_SHOW_SQL: "true"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://magazzino-eureka:8761/eureka/"
      AUTH_JWT_SECRET: "${AUTH_JWT_SECRET}"
    ports:
      - "8782:8080"
    depends_on:
      sqlserver-db:
        condition: service_healthy
      init-db:
        condition: service_completed_successfully
      magazzino-eureka:
        condition: service_started

  clienti:
    build:
      context: ./ClientiService
          
    container_name: clienticontainer
    environment: 
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://sqlserver-db:1433;databaseName=DBMAGAZZINI;encrypt=true;trustServerCertificate=true"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "Magazzinetto34*"
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      SPRING_JPA_SHOW_SQL: "true"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://magazzino-eureka:8761/eureka/"
    ports:
      - "9090:8080"
    depends_on:
      sqlserver-db:
        condition: service_healthy
      init-db:
        condition: service_completed_successfully
      magazzino-eureka:
        condition: service_started
  prodotti:
    build:
      context: ./ProdottiService
    container_name: prodotticontainer
    environment: 
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://sqlserver-db:1433;databaseName=DBMAGAZZINI;encrypt=true;trustServerCertificate=true"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "Magazzinetto34*"
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      SPRING_JPA_SHOW_SQL: "true"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://magazzino-eureka:8761/eureka/"
    ports:
      - "9091:8080"
    depends_on:
      sqlserver-db:
        condition: service_healthy
      init-db:
        condition: service_completed_successfully
      magazzino-eureka:
        condition: service_healthy
  ordini:
    build:
      context: ./OrdiniService
    container_name: ordinicontainer
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://sqlserver-db:1433;databaseName=DBMAGAZZINI;encrypt=true;trustServerCertificate=true"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "Magazzinetto34*"
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      SPRING_JPA_SHOW_SQL: "true"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://magazzino-eureka:8761/eureka/"
    ports:
      - "9092:8080"
    depends_on:
      sqlserver-db:
        condition: service_healthy
      init-db:
        condition: service_completed_successfully
      magazzino-eureka:
        condition: service_healthy
  
  apigateway:
    build:
      context: ./apigateway
    container_name: apigatewaycontainer
    environment:
      AUTH_JWT_SECRET: "${AUTH_JWT_SECRET}"
    ports:
      - "8088:8080"
    depends_on:
      init-db:
        condition: service_completed_successfully
      auth:
        condition: service_started
      clienti:
        condition: service_started
      prodotti:
        condition: service_started
      ordini:
        condition: service_started
      magazzino-eureka:
        condition: service_healthy
        
  magazzino-eureka:
    build:
      context: ./ServiceDiscovery
    container_name: magazzino-eureka-container
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_NAME: "eureka-server"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      SERVER_PORT: "8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s
      
volumes:
  sqlserver_data:      