spring:
  application:
    name: SpedizioniService
  kafka:
    channels:
      ordini: ordini-channel
    consumer:
      group-id: SpedizioniService
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties: 
        spring:
          json:
            trusted:
              packages: it.personalproject.ordini.domain.events
                

  datasource:
    url: jdbc:sqlserver://sqlserver-db:1433;databaseName=DBMAGAZZINI;encrypt=true;trustServerCertificate=true
    username: admin
    password: magazzinetto34
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

server:
  port: 8080
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://magazzino-eureka:8761/eureka
      
---
spring:
  config:
    activate:
      on-profile: dev


---
spring:
  config:
    activate:
      on-profile: "!dev"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/magazzino