server:
  port: 8080

spring:
  application:
    name: apigateway

  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: clienti
          uri: lb://ClientiService
          predicates:
            - Path=/api/clienti/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: clientiCB
                fallbackUri: forward:/fallback/clienti

        - id: prodotti
          uri: lb://ProdottiService
          predicates:
            - Path=/api/prodotti/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: prodottiCB
                fallbackUri: forward:/fallback/prodotti

        - id: ordini
          uri: lb://OrdiniService
          predicates:
            - Path=/api/ordini/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: ordiniCB
                fallbackUri: forward:/fallback/ordini

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false

  main:
    web-application-type: reactive
  webflux:
    base-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://magazzino-eureka:8761/eureka